version: '3'

services:
    webmail-postgres:
        image: postgres:12
        container_name: "webmail-postgres"
        env_file:
            - .envs/base.env
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    webmail-django:
        build: .
        container_name: "webmail-django"
        env_file:
            - .envs/base.env
            - .envs/django.env
            - .envs/email.env
        ports:
            - "8000:8000"
        volumes:
            - .:/webmail
        depends_on:
            - webmail-postgres
        
volumes:
    postgres-data:
