# Generated by Django 3.1 on 2020-09-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('msg_id', models.CharField(max_length=255)),
                ('mailbox', models.CharField(max_length=255)),
                ('sent_on', models.DateTimeField()),
                ('sent_from', models.JSONField()),
                ('sent_to', models.JSONField()),
                ('cc', models.JSONField()),
                ('bcc', models.JSONField()),
                ('subject', models.CharField(max_length=255, null=True)),
                ('body_plain', models.TextField(null=True)),
                ('body_html', models.TextField(null=True)),
            ],
        ),
    ]
